[tool.poetry]
name = "TDTK"
version = "0.1.0"
description = ""
authors = ["Jhon Diaz <electimon@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
adbutils = "^2.0.1"
progress = "^1.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
